repl-datastructures:
	idris -p lightyear DataStructures.idr

repl-lexer:
	idris -p lightyear Lexer.idr

repl-parser:
	idris -p lightyear Parser.idr

repl-expr:
	idris -p lightyear Expr.idr

exec:
	echo ':exec (Lightyear.Strings.parse (expression ) "(1+2)*3")' | idris -p lightyear imp.idr
