repl-datastructures:
	idris -p lightyear datastructures.idr

repl-lexer:
	idris -p lightyear Lexer.idr

exec:
	echo ':exec (Lightyear.Strings.parse (expression ) "(1+2)*3")' | idris -p lightyear imp.idr
